project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  description: "A blog built with Quarto"
  site-url: https://codyveladev.github.io/cody-learns-data # you must change this appropriately for RSS feeds to work properly
  title: "Cody Learns Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - flatly
    css: styles.css
    highlight-style: github
    code-copy: true
    code-overflow: wrap



